JAVA=javac

OBJECTS=HelloWorld StringTest ClassInherit

all: ${OBJECTS}

HelloWorld: HelloWorld.java
	${JAVA} HelloWorld.java

StringTest: StringTest.java
	${JAVA} StringTest.java

ClassInherit: ClassInherit.java
	${JAVA} ClassInherit.java

clean:
	rm ./*.class
